# Generated by Django 5.2.4 on 2025-08-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patrimonio',
            options={'verbose_name_plural': 'Patrimônios'},
        ),
        migrations.RemoveField(
            model_name='patrimonio',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='categoria',
            field=models.CharField(choices=[('Equipamento de Produção', 'Equipamento de Produção'), ('Mobiliário', 'Mobiliário'), ('Utensílios', 'Utensílios')], default='Equipamento de Produção', max_length=50),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='data_manutencao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Manutenção'),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='status',
            field=models.CharField(choices=[('Em Uso na Produção', 'Em Uso na Produção'), ('Em Manutenção', 'Em Manutenção'), ('Desativado', 'Desativado')], default='Em Uso na Produção', max_length=20),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='condicao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aquisição'),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
