# Generated by Django 5.2.4 on 2025-08-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0002_alter_patrimonio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonio',
            name='arquivo_nota',
            field=models.FileField(blank=True, null=True, upload_to='notas_fiscais/', verbose_name='Arquivo da Nota (PDF)'),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número da Nota Fiscal'),
        ),
    ]
