# Generated by Django 5.2.4 on 2025-08-04 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='preco_por_unidade',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Preço de venda por unidade do produto gerado', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
