# Generated by Django 5.2.4 on 2025-08-12 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_preco_por_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='descricao',
        ),
        migrations.AddField(
            model_name='itemreceita',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Custo total deste item', max_digits=10),
        ),
        migrations.AddField(
            model_name='itemreceita',
            name='fator_correcao',
            field=models.FloatField(default=1.0, help_text='Fator de correção (ex.: 1.0 para sem perda)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='itemreceita',
            name='peso_bruto',
            field=models.FloatField(blank=True, help_text='Peso bruto do ingrediente', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='itemreceita',
            name='peso_liquido',
            field=models.FloatField(blank=True, help_text='Peso líquido após correção', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='itemreceita',
            name='unidade',
            field=models.CharField(default='KG', help_text='Unidade de medida', max_length=10),
        ),
        migrations.AddField(
            model_name='itemreceita',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor unitário do ingrediente', max_digits=10),
        ),
        migrations.AddField(
            model_name='receita',
            name='custo_por_porcao',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='receita',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='receita',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto do prato preparado', null=True, upload_to='receitas/'),
        ),
        migrations.AddField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(blank=True, help_text='Passos para preparar a receita'),
        ),
        migrations.AddField(
            model_name='receita',
            name='profissional',
            field=models.CharField(blank=True, help_text='Nome do profissional responsável', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='rendimento',
            field=models.PositiveIntegerField(default=1, help_text='Número de porções geradas'),
        ),
        migrations.AlterField(
            model_name='itemreceita',
            name='quantidade',
            field=models.FloatField(help_text='Quantidade base', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
