# Generated by Django 5.2.4 on 2025-08-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_remove_receita_descricao_itemreceita_custo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receita',
            options={},
        ),
        migrations.AlterField(
            model_name='itemreceita',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='itemreceita',
            name='fator_correcao',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemreceita',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemreceita',
            name='peso_liquido',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemreceita',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemreceita',
            name='unidade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='itemreceita',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='custo_por_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receita',
            name='preco_por_unidade',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receita',
            name='profissional',
            field=models.CharField(blank=True, default=0.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='quantidade_produzida',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receita',
            name='rendimento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
