# Generated by Django 5.2.4 on 2025-08-14 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_alter_receita_options_alter_itemreceita_custo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receita',
            options={'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='modo_preparo',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='itemreceita',
            name='custo',
        ),
        migrations.RemoveField(
            model_name='itemreceita',
            name='fator_correcao',
        ),
        migrations.RemoveField(
            model_name='itemreceita',
            name='peso_bruto',
        ),
        migrations.RemoveField(
            model_name='itemreceita',
            name='peso_liquido',
        ),
        migrations.RemoveField(
            model_name='itemreceita',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='itemreceita',
            name='valor_unitario',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='custo_por_porcao',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='custo_total',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='profissional',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='rendimento',
        ),
        migrations.AlterField(
            model_name='itemreceita',
            name='quantidade',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='preco_por_unidade',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Preço de venda por unidade do produto gerado', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='receita',
            name='quantidade_produzida',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade de produtos gerados por receita'),
        ),
    ]
