# Generated by Django 5.2.4 on 2025-08-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_alter_receita_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreceita',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemreceita',
            name='fator_correcao',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='itemreceita',
            name='quantidade_bruta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemreceita',
            name='quantidade_liquida',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemreceita',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='custo_por_porcao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='receita',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='receita',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/'),
        ),
        migrations.AddField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(blank=True, help_text='Modo de preparo, um passo por linha.'),
        ),
        migrations.AddField(
            model_name='receita',
            name='profissional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='rendimento',
            field=models.IntegerField(default=20, help_text='Número de porções.'),
        ),
    ]
