# Generated by Django 5.2.4 on 2025-07-30 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_producao', models.DateTimeField(auto_now_add=True)),
                ('quantidade_produzida', models.PositiveIntegerField(default=1, help_text='Número de receitas produzidas')),
                ('produto_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.receita')),
            ],
            options={
                'verbose_name': 'Fornada',
                'verbose_name_plural': 'Fornadas',
            },
        ),
    ]
