# Generated by Django 5.2.4 on 2025-07-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornada',
            name='quantidade_produzida',
            field=models.PositiveIntegerField(default=1, help_text='Número de unidades produzidas'),
        ),
    ]
