# Generated by Django 5.2.4 on 2025-08-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornadas', '0002_alter_fornada_quantidade_produzida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornada',
            name='quantidade_produzida',
            field=models.PositiveIntegerField(default=1, help_text='Número de execuções da receita'),
        ),
    ]
