# Generated by Django 5.2.4 on 2025-08-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornadas', '0003_alter_fornada_quantidade_produzida'),
        ('receitas', '0004_alter_receita_options_alter_itemreceita_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornada',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornadas', to='receitas.receita'),
        ),
    ]
