# Generated by Django 5.2.4 on 2025-08-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Kg'), ('l', 'Litro'), ('pacote', 'Pacote')], max_length=50)),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
