# Generated by Django 5.2.4 on 2025-08-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name_plural': 'Insumos'},
        ),
        migrations.AddField(
            model_name='insumo',
            name='arquivo_nota',
            field=models.FileField(blank=True, null=True, upload_to='notas_insumos/', verbose_name='Arquivo da Nota (PDF)'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('Embalagem', 'Embalagem'), ('Pacote de Ingrediente', 'Pacote de Ingrediente'), ('Outros', 'Outros')], default='Embalagem', max_length=50),
        ),
        migrations.AddField(
            model_name='insumo',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aquisição'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='numero_nota',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número da Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='status',
            field=models.CharField(choices=[('Em Estoque', 'Em Estoque'), ('Em Uso', 'Em Uso'), ('Esgotado', 'Esgotado')], default='Em Estoque', max_length=20),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Insumo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Unitário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insumo',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='quantidade_minima',
            field=models.PositiveIntegerField(verbose_name='Quantidade Mínima'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidade_medida',
            field=models.CharField(max_length=50, verbose_name='Unidade de Medida'),
        ),
    ]
