# Generated by Django 5.2.4 on 2025-07-30 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('quantidade_estoque', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unidade_medida', models.CharField(max_length=20)),
                ('quantidade_minima', models.FloatField(help_text='Quantidade mínima para alerta', validators=[django.core.validators.MinValueValidator(0)])),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
