# Generated by Django 5.2.4 on 2025-07-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
    ]
