# Generated by Django 5.2.4 on 2025-08-02 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0002_alter_ingrediente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='quantidade_estoque',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='quantidade_minima',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Quantidade mínima para alerta', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidade_medida',
            field=models.CharField(choices=[('kg', 'Kilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidade')], max_length=10),
        ),
    ]
