# Generated by Django 5.2.4 on 2025-08-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastofixo',
            name='dia_pagamento',
            field=models.PositiveSmallIntegerField(default=1, help_text='Dia do mês para pagamento (1-31)'),
        ),
    ]
