# Generated by Django 5.2.4 on 2025-08-07 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_gastofixo_dia_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='quantidade_comprada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
